# File: config/facebooker-mock.yml
# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port

development:
 api_key: 2b1c5fd3ca446d22bce5ca37ea877c39 
 secret_key: e45016cc0401ac8c866222a176f63fc7
 canvas_page_name: zacknmiri    
 callback_url: http://chowder.msponge.com:8111
 tunnel:
     public_host_username:  
     public_host:
     public_port: 8111
     local_port: 8111    
test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
production:
  api_key: 
  secret_key: 
  canvas_page_name: 
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000 